#ifndef FRONTEND_ICONS_H
#define FRONTEND_ICONS_H

#define MSE_ICON_HOME "\xEF\x91\xAD"
#define MSE_ICON_SYSTEMS "\xE2\x8C\x82"
#define MSE_ICON_UPDATE_ALL "\xE2\x9F\xB3"
#define MSE_ICON_FETCH_CORES "\xEF\x80\x99"
#define MSE_ICON_START_CORE "\xE2\x96\xB6"
#define MSE_ICON_UPDATE "\xEF\x83\xAD"
#define MSE_ICON_REMOVE "\xEF\x80\x8D"
#define MSE_ICON_OPTIONS "\xE2\x9A\x99"
#define MSE_ICON_INFO "\xEF\x91\x89"
#define MSE_ICON_CAPS "\xEE\x9A\x90"
#define MSE_ICON_INSTALLED "\xE2\x9C\x93"
#define MSE_ICON_NEEDS_UPDATE "\xEF\x83\xAD"
#define MSE_ICON_DOWNLOAD "\xEF\x80\x99"
#define MSE_ICON_SETTINGS "\xEF\x80\x93"
#define MSE_ICON_CONTROLLER "\xF3\xB0\xAE\x82"
#define MSE_ICON_KEYBOARD "\xEF\x84\x9C"
#define MSE_ICON_APPEARANCE "\xEF\x87\xBC"
#define MSE_ICON_WRENCH "\xEF\x82\xAD"
#define MSE_ICON_POWER "\xEF\x80\x91"
#define MSE_ICON_VIDEO "\xF3\xB0\x8D\xB9"
#define MSE_ICON_VOLUME_LOW "\xEF\x80\xA7"
#define MSE_ICON_VOLUME_HIGH "\xEF\x80\xA8"
#define MSE_ICON_VOLUME_OFF "\xEF\x80\xA6"
#define MSE_ICON_VOLUME_MUTE "\xEE\xBB\xA8"
#define MSE_ICON_TERMINAL "\xF3\xB0\x8D\xB9"
#define MSE_ICON_LIBRARY "\xEE\xAE\x9C"
#define MSE_ICON_BACKENDS "\xEF\x92\xBC"
#define MSE_ICON_BIOS "\xE2\xA7\x81"
#define MSE_ICON_MEMVIEW "\xE2\xA8\xB1"
#define MSE_ICON_LOGS "\xEF\x83\xB6"

#endif // FRONTEND_ICONS_H